services:
  # Background worker for email enrichment processing
  - type: web
    name: email-enrichment-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py serve --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project
      # Logging
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE_ENABLED
        value: true
      - key: LOG_FILE_PATH
        value: ./logs
      - key: LOG_ROTATION
        value: "10 MB"
      - key: LOG_RETENTION
        value: "30 days"
      # Service Configuration
      - key: MAX_WORKERS
        value: 1
      - key: BATCH_SIZE
        value: 10
      - key: JOB_POLLING_INTERVAL
        value: 30
      - key: REQUEST_TIMEOUT
        value: 30
      # Processing Limits
      - key: MAX_EMAILS_PER_DOMAIN
        value: 3
      - key: HUNTER_CONFIDENCE_THRESHOLD
        value: 70
      - key: VERIFICATION_CONFIDENCE_THRESHOLD
        value: 65
      # Rate Limiting
      - key: HUNTER_RATE_LIMIT
        value: 3
      - key: PERPLEXITY_RATE_LIMIT
        value: 30
      # Database Configuration
      - key: DB_CONNECTION_POOL_SIZE
        value: 10
      - key: DB_CONNECTION_TIMEOUT
        value: 30
      # Service Configuration
      - key: SERVICE_NAME
        value: "email-enrichment-service"
      # Development settings
      - key: DEBUG_MODE
        value: false
      - key: DRY_RUN
        value: false
      # Database connection
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      # API Keys
      - key: HUNTER_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
